# About me
## _Wang Luting_


a student from Hokkaido University doing some research about sharing economy, especially P2P accommodation.

- Impacts of Airbnb
- SDGs
- ✨Hawaii and Japan

## What else

- Loving story 
- loving music
